# Setup
title:               NHL data analysis Milestone 1 team B-14
tagline:             'A template based on the Lanyon Jekyll theme'
description:         'Here we present our analysis for the first Milestone of the NHL data analysis project.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kaiqi Cheng
  email:             kaiqi.cheng@umontreal.ca
  name:              Milosh Devic
  email:             milosh.devic@umontreal.ca
  name:              Yonglin Zhu
  email:             yonglin.zhu@umontreal.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
